### ISSUE TITLE
Define instructor routes

### ISSUE THREAD

**Issue by brunolpsousa** [motiro/motiro-study-system#6]
Mandatory:
- [x] Create instructor
- [x] Update instructor
- [x] List instructor (it is not specified whether it should be a particular instructor or all instructors)
- [x] Delete instructor

**Comment by gabrielleeee** [comment]
GET/api/v1/instructor -> Retrieves all instructors

GET/api/v1/instructor/:id -> Retrieves one instructor by id

POST/api/v1/instructor -> Create a new instructor

PATCH/api/v1/instructor/:id -> Updates a instructor

DELETE/api/v1/instructor/:id -> Deletes a instructor
