### ISSUE TITLE
Define student routes

### ISSUE THREAD

**Issue by brunolpsousa** [motiro/motiro-study-system#7]
Mandatory:
- [x] Create student
- [x] Update student
- [x] List student (it is not specified whether it should be a particular student or all students)
- [x] Delete student

**Comment by gabrielleeee** [comment]
GET/api/v1/student -> Retrieves all student

GET/api/v1/student/:id -> Retrieves one student by id

POST/api/v1/student -> Create a new student

PATCH/api/v1/student/:id -> Updates a student

DELETE/api/v1/student/:id -> Deletes a student
